name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v3
      -  uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ secrets.GHCR_USER }}
           password: ${{ secrets.GHCR_TOKEN }}

      -  uses: docker/setup-buildx-action@v3
      -  name: Publish
         uses: docker/build-push-action@v6
         with:
           context: .
           file: ./Dockerfile
           push: true
           tags: |
             ghcr.io/${{ secrets.GHCR_USER }}/brewapi:latest
           platforms: linux/amd64, linux/arm64
           
